/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Controler.Shop;
import Exception.DAO_Excep;
import Exception.ProductExepcion;
import Exception.ProductExepcion;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Amount;
import static model.Ficheros.LecturaFichero;
import model.Product;
/**
 *si a
 * @author Estudio-Trabajo
 */
public class ProductView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProductView.class.getName());
    private Shop shop;
    private JFrame ventanaAnterior;
    private int opcion;
    /**
     * Creates new form AddProduct
     */
    public ProductView(JFrame anterior, Shop ShopExistente, int opcionRecibida) {
        initComponents();
        this.ventanaAnterior = anterior;
        this.shop = ShopExistente;
        this.getRootPane().setDefaultButton(Action);
        this.opcion = opcionRecibida;
        if(opcionRecibida == 2){
            Nompr.setVisible(true); NombreProducto.setVisible(true);
            Preciopr.setVisible(true); PrecioProducto.setVisible(true);
            Stockpr.setVisible(true); StockProducto.setVisible(true);
            this.setTitle("Añadir Nuevo Producto");
        } else if (opcionRecibida == 3){
           Nompr.setVisible(true); NombreProducto.setVisible(true);
            Preciopr.setVisible(false); PrecioProducto.setVisible(false);
            Stockpr.setVisible(true); StockProducto.setVisible(true); 
            this.setTitle("Añadir Stock");
        }else if (opcionRecibida == 9){
            Nompr.setVisible(true); NombreProducto.setVisible(true);
            Preciopr.setVisible(false); PrecioProducto.setVisible(false);
            Stockpr.setVisible(false); StockProducto.setVisible(false);
            this.setTitle("Eliminar producto");
        }
        
       

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                if (ventanaAnterior != null) {
                    ventanaAnterior.setVisible(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nompr = new javax.swing.JLabel();
        Stockpr = new javax.swing.JLabel();
        Preciopr = new javax.swing.JLabel();
        StockProducto = new javax.swing.JTextField();
        PrecioProducto = new javax.swing.JTextField();
        NombreProducto = new javax.swing.JTextField();
        Action = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Nompr.setText("Nombre del producto:");

        Stockpr.setText("Stock Producto:");

        Preciopr.setText("Precio Producto:");

        StockProducto.setColumns(20);

        PrecioProducto.setColumns(20);

        NombreProducto.setColumns(20);
        NombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProductoActionPerformed(evt);
            }
        });

        Action.setText("OK");
        Action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Nompr, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(Stockpr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Preciopr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Action)
                .addGap(37, 37, 37)
                .addComponent(Cancelar)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nompr)
                    .addComponent(NombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Stockpr)
                    .addComponent(StockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Preciopr)
                    .addComponent(PrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Action)
                    .addComponent(Cancelar))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProductoActionPerformed

    private void ActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionActionPerformed
        // TODO add your handling code here:
        
        String producto = NombreProducto.getText();
                boolean aviable =true;
                int stock = Integer.parseInt(StockProducto.getText());
                Amount price = new Amount(Double.parseDouble(PrecioProducto.getText()));
                int id =1;
                Product p = new Product(id, producto, aviable, stock, price);
        try {
            if (opcion == 2) {
                
                shop.addProduct(id,p);
                id++;
                JOptionPane.showMessageDialog(this, "Producto añadido correctamente", "Addproduct", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
               

            } else if (opcion == 3) {

                int upStock = Integer.parseInt(StockProducto.getText());
                shop.addStock(p, stock);
                JOptionPane.showMessageDialog(this, "Stock modificado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                
            } else if (opcion == 9) {

                shop.deleteProduct(p);
                JOptionPane.showMessageDialog(this, "Producto eliminado", "Correcto", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Introduce numeros validos.");
            limpiarCampos();
        } catch (ProductExepcion e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
            limpiarCampos();
        }catch (DAO_Excep e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            
        }

 
        
    }//GEN-LAST:event_ActionActionPerformed

    private void limpiarCampos() {
    NombreProducto.setText("");
    StockProducto.setText("");
    PrecioProducto.setText("");
    // Opcional: Poner el foco de nuevo en el nombre para empezar de nuevo
    NombreProducto.requestFocus();
}
    
    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProductView(null, new Shop(), 0).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Action;
    private javax.swing.JButton Cancelar;
    private javax.swing.JTextField NombreProducto;
    private javax.swing.JLabel Nompr;
    private javax.swing.JTextField PrecioProducto;
    private javax.swing.JLabel Preciopr;
    private javax.swing.JTextField StockProducto;
    private javax.swing.JLabel Stockpr;
    // End of variables declaration//GEN-END:variables
}
